services:
  vscode-server-default:
    image: ghcr.io/declue/vscode-server:default
    container_name: vscode-server-default
    build:
      context: .
      dockerfile: Dockerfile_default
    ports:
    - "28080:8080"
    environment:
    - "PASSWORD=changeit"

  vscode-server-python:
    image: ghcr.io/declue/vscode-server:python
    container_name: vscode-server-python
    build:
      context: .
      dockerfile: Dockerfile_python
    ports:
    - "28081:8080"
    environment:
    - "PASSWORD=changeit"
    depends_on:
    - vscode-server-default

