FROM ghcr.io/declue/vscode-server:default

# nodejs 설치
RUN curl -fsSL https://deb.nodesource.com/setup_18.x | sudo -E bash - && sudo apt-get install -y nodejs

# yarn 설치
RUN sudo apt-get install -y gcc g++ make iputils-ping httpie nodejs && \
    curl -sL https://dl.yarnpkg.com/debian/pubkey.gpg | sudo apt-key add - && \
    echo "deb https://dl.yarnpkg.com/debian/ stable main" | sudo tee /etc/apt/sources.list.d/yarn.list && \
    sudo apt-get install -y yarn && \
    sudo apt-get upgrade -y

USER developer

ADD nodejs-extensions.txt /tmp/nodejs-extensions.txt

RUN cat /tmp/nodejs-extensions.txt | while read -r line; do code-server --install-extension $line; done

USER root


