FROM ghcr.io/declue/docker_ubuntu:20.04

RUN apt-get update

# 필수 패키지 설치
RUN apt-get install -y dumb-init zsh htop locales man nano git procps openssh-client sudo jq openssl bash-completion dnsutils lsb-release cscope
RUN apt-get install -y python3 python3-pip python3-dev build-essential python-is-python3
RUN apt-get install -y openjdk-11-jdk


# user "code" 생성 및 workspace 생성
RUN addgroup --gid 1000 developer
RUN adduser --uid 1000 --ingroup developer --home /home/developer --shell /bin/bash --disabled-password --gecos "" developer
RUN adduser developer sudo
RUN chmod g+rw /home 
RUN mkdir -p /home/developer/workspace
RUN chown developer:developer /home/developer/workspace -R
RUN echo '%sudo ALL=(ALL) NOPASSWD:ALL' >> /etc/sudoers;


# fluxid 설치 (2023-01-18자로 최신 버전은 0.5.1)
RUN USER=docker && \
    GROUP=docker && \
    curl -SsL https://github.com/boxboat/fixuid/releases/download/v0.5.1/fixuid-0.5.1-linux-amd64.tar.gz | tar -C /usr/local/bin -xzf - && \
    chown root:root /usr/local/bin/fixuid && \
    chmod 4755 /usr/local/bin/fixuid && \
    mkdir -p /etc/fixuid && \
    printf "user: $USER\ngroup: $GROUP\n" > /etc/fixuid/config.yml


# install code-server 4.9.1 (2023-01-18 최신 버전)
ENV CODE_SERVER_VERSION=4.9.1
ENV ARCH=amd64
RUN curl -sSOL https://github.com/coder/code-server/releases/download/v${CODE_SERVER_VERSION}/code-server_${CODE_SERVER_VERSION}_amd64.deb
RUN sudo dpkg -i code-server_${CODE_SERVER_VERSION}_${ARCH}.deb

# default home 
RUN mkdir /opt/default_home
ADD .bashrc /opt/default_home

# script
ADD code.sh /usr/local/bin/code
ADD startup.sh /startup.sh

RUN chmod a+x /usr/local/bin/*

EXPOSE 8080

WORKDIR /home/developer/workspace

ENTRYPOINT ["/bin/bash", "/startup.sh"]

