apiVersion: v1
kind: Secret
metadata:
  name: {{ include "default.fullname" . }}
  labels:
    app: {{ include "default.fullname" . }}
    chart: "{{ .Chart.Name }}-{{ .Chart.Version }}"
    release: "{{ .Release.Name }}"
    heritage: "{{ .Release.Service }}"
type: Opaque
data:
  {{ if .Values.secret.password }}
  PASSWORD: {{ .Values.secret.password | b64enc | quote }}
  {{ else }}
  PASSWORD: {{ randAlphaNum 10 | b64enc | quote }}
  {{ end }}
